#! /bin/sh
picom --experimental-backends &
$HOME/.config/polybar/launch.sh &
$HOME/.config/bspwm/bspi/bspi_listen &
~/.fehbg &
sxhkd &

bspc monitor -d "" "" "" "" "" "" "" "" "" ""

bspc config border_width         2
bspc config window_gap          12
bspc config pointer_motion_interval 10
bspc config focused_border_color    '#d8dee9'
bspc config normal_border_color     '#4c566a'
bspc config presel_feedback_color   '#88c0d0'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a feh state=floating
# bspc rule -a Pcmanfm state=floating